export const forgeFairLaunchFactoryAbi = [
  {
    type: "function",
    name: "createLaunch",
    stateMutability: "payable",
    inputs: [
      {
        name: "params",
        type: "tuple",
        components: [
          { name: "token", type: "address" },
          { name: "currency", type: "uint8" },
          { name: "tokensForSale", type: "uint256" },
          { name: "softCap", type: "uint256" },
          { name: "hardCap", type: "uint256" },
          { name: "maxContribution", type: "uint256" },
          { name: "startTime", type: "uint64" },
          { name: "endTime", type: "uint64" },
          { name: "liquidityPercent", type: "uint16" },
          { name: "autoListing", type: "bool" },
          { name: "routerKind", type: "uint8" },
          { name: "v3Fee", type: "uint24" },
          { name: "lockDuration", type: "uint256" },
          { name: "whitelistRoot", type: "bytes32" },
          { name: "whitelistEnabled", type: "bool" },
          { name: "metadataURI", type: "string" },
        ],
      },
    ],
    outputs: [{ type: "address" }],
  },
  { type: "function", name: "creationFee", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "treasury", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "usdcToken", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  {
    type: "function",
    name: "routerConfig",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "routerV2", type: "address" },
          { name: "factoryV2", type: "address" },
          { name: "wrappedNative", type: "address" },
          { name: "v3Factory", type: "address" },
          { name: "v3PoolDeployer", type: "address" },
          { name: "v3Migrator", type: "address" },
          { name: "positionManager", type: "address" },
        ],
      },
    ],
  },
  { type: "function", name: "launchCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "launchAt",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "event",
    name: "FairLaunchCreated",
    inputs: [
      { name: "pool", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "token", type: "address", indexed: true },
      { name: "currency", type: "uint8", indexed: false },
      { name: "tokensForSale", type: "uint256", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
    ],
    anonymous: false,
  },
] as const;
